sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t docker_travis_test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run docker_travis_test npm test -- --coverage

after_success:
  - docker build -t maksim1990/multi-client ./client
  - docker build -t maksim1990/multi-server ./server
  - docker build -t maksim1990/multi-nginx ./nginx
  - docker build -t maksim1990/multi-worker ./worker

  # Login to Docker CLI
  - echo "korncoms050419909111" | docker login -u "maksim1990" --password-stdin

  # Push images to Docker Hub
  - docker push maksim1990/multi-client
  - docker push maksim1990/multi-server
  - docker push maksim1990/multi-nginx
  - docker push maksim1990/multi-worker
